version: '3.8'
services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - './dbdata:/var/lib/postgresql/data'
    env_file:
      - .env.docker
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
      - db
      - redis
      - mosquitto
    volumes:
      - .:/app
    env_file:
      - .env.docker
    environment:
      - RAILS_ENV=production
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
      - mosquitto
    env_file:
      - .env.docker
    environment:
      - RAILS_ENV=production
    volumes:
      - .:/app
  mosquitto:
    image: 'eclipse-mosquitto:latest'
    ports:
      - '1883:1883'
    volumes:
      - ./config:/mosquitto/config
      - ./log:/mosquitto/log/
      - ./data:/mosquitto/data/
volumes:
  dbdata:
