version: '3.8'
services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - './dbdata:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=password
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  sidekiq:
    depends_on:
      - db
      - redis
      - mosquitto
    build: .
    command: 'sidekiq:start'
    volumes:
      - '.:/project'
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
  #      - RAILS_ENV=production
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
      - sidekiq
      - mosquitto
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - REDIS_URL=redis://redis:6379
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
    #      - RAILS_ENV=production
    volumes:
      - .:/app
  mosquitto:
    image: 'eclipse-mosquitto:latest'
    ports:
      - '1883:1883'
    volumes:
      - ./config:/mosquitto/config
      - ./log:/mosquitto/log/
      - ./data:/mosquitto/data/
volumes:
  dbdata:
