default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: earthchip_development

test:
  <<: *default
  database: earthchip_test

production:
  <<: *default
  database: earthchip_production
  username: earthchip
  password: <%= ENV['EARTHCHIP_DATABASE_PASSWORD'] %>
